# SITE CONFIGURATION
title: Orbital Surveys # your site title
author: Cayle sharrock # You :P
description: > # Meta description of Homepage
  Orbital Survey is a GPS oriented survey company which has been providing a service to the mapping and mining industry
  since 1995. We are a small organization utilising state of the art technology to provide the client with a cost
  effective total survey solution. Our core function is that of high quality GPS surveys and digital mapping services
  and through an affiliation of expert complementary companies, can provide a wide range of mapping related services.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gps.co.za/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Orbital Surveys
  links:

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Mapping and aerial photography solutions

hero_img: ortho_1920x1080.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: orbital@mweb.co.za # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
#instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: false

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
